let lessons = [
{ "id": 1, 
  "subject":"Math", 
  "location":"California", 
  "price":100, 
  "spaces":5,
  "image":"images/math.png" },
{ "id": 2, 
  "subject":"Physics", 
  "location":"Arizona", 
  "price":120, 
  "spaces":5,
  "image":"images/physics.png"},
{ "id": 3, 
  "subject":"Chemistry", 
  "location":"New York", 
  "price":95, 
  "spaces":5,
  "image":"images/chemistry.png"},
{ "id": 4, 
  "subject":"English", 
  "location":"Texas", 
  "price":80, 
  "spaces":5,
  "image":"images/english.png"},
{ "id": 5, 
  "subject":"Art", 
  "location":"Washington D.C", 
  "price":70, 
  "spaces":5,
  "image":"images/art.png"},
  { "id": 6, 
  "subject":"Music", 
  "location":"Los Angeles", 
  "price":85, 
  "spaces":5,
  "image":"images/music.png" },
{ "id": 7, 
  "subject":"Biology", 
  "location":"Illinois", 
  "price":110, 
  "spaces":5,
  "image":"images/biology.png"},
{ "id": 8, 
  "subject":"History", 
  "location":"Alaska", 
  "price":75, 
  "spaces":5,
  "image":"images/history.png"},
{ "id": 9, 
  "subject":"PE", 
  "location":"Ohio", 
  "price":60, 
  "spaces":5,
  "image":"images/pe.png"},
{ "id":10, 
  "subject":"Computing", 
  "location":"Hawaii", 
  "price":130, 
  "spaces":5,
  "image":"images/computing.png"}
];