let lessons = [
{ "id": 1, 
  "subject":"Mathematics & Analytical Reasoning", 
  "location":"California", 
  "price":100, 
  "spaces":5,
  "image":"images/math.png",
  "rating": 5 },
{ "id": 2, 
  "subject":"Physics & Applied Physical Sciences", 
  "location":"Arizona", 
  "price":120, 
  "spaces":5,
  "image":"images/physics.png",
  "rating": 5},
{ "id": 3, 
  "subject":"Chemistry & Molecular Sciences", 
  "location":"New York", 
  "price":95, 
  "spaces":5,
  "image":"images/chemistry.png",
  "rating": 3},
{ "id": 4, 
  "subject":"Languages & Communication Studies", 
  "location":"Texas", 
  "price":80, 
  "spaces":5,
  "image":"images/english.png",
  "rating": 3},
{ "id": 5, 
  "subject":"Creative Arts & Design", 
  "location":"Washington D.C", 
  "price":70, 
  "spaces":5,
  "image":"images/art.png",
  "rating": 4},
  { "id": 6, 
  "subject":"Music & Performing Arts Studies", 
  "location":"Los Angeles", 
  "price":85, 
  "spaces":5,
  "image":"images/music.png",
  "rating": 2},
{ "id": 7, 
  "subject":"Biology & Life Sciences", 
  "location":"Illinois", 
  "price":110, 
  "spaces":5,
  "image":"images/biology.png",
  "rating": 4},
{ "id": 8, 
  "subject":"History, Geography & Social Studies", 
  "location":"Alaska", 
  "price":75, 
  "spaces":5,
  "image":"images/history.png",
  "rating": 2},
{ "id": 9, 
  "subject":"Health, Wellness & Physical Education", 
  "location":"Ohio", 
  "price":60, 
  "spaces":5,
  "image":"images/pe.png",
  "rating": 5},
{ "id":10, 
  "subject":"Computer Science & Information Technology", 
  "location":"Hawaii", 
  "price":130, 
  "spaces":5,
  "image":"images/computing.png",
  "rating": 5}
];